"""
config.yaml Auto-Generator

Automatically generates domain-specific config.yaml
based on process.md and information collected from conversation.

Usage:
    config = generate_config(
        domain_name="my-domain",
        display_name="NSE X-Ray Inspection Equipment CS",
        document_paths=["c:/path/to/docs"],
        workspace="nse_cs"
    )
    save_config(config, "domains/my-domain/config.yaml")
"""

import yaml
from pathlib import Path


def generate_config(
    domain_name: str,
    display_name: str,
    description: str = "",
    document_paths: list[str] = None,
    workspace: str = "",
    crystallization_settings: dict = None
) -> dict:
    """Generates the content of a domain config.yaml.

    Args:
        domain_name: Domain name (e.g., "my-domain")
        display_name: Display name
        description: Domain description
        document_paths: List of document folder paths for indexing
        workspace: Workspace name
        crystallization_settings: Crystallization settings override
    """
    if not workspace:
        workspace = domain_name.replace("-", "_")

    if not crystallization_settings:
        crystallization_settings = {
            "auto_log": True,
            "auto_extract": True,
            "promotion": {
                "min_usage": 5,
                "min_success_rate": 0.8,
                "auto_promote": True
            },
            "schedule": {
                "realtime": ["log", "extract", "usage_stats"],
                "weekly": ["promote", "report"],
                "monthly": ["export"]
            }
        }

    config = {
        "domain": {
            "name": domain_name,
            "display_name": display_name,
            "description": description or f"{display_name} domain"
        },
        "documents": {
            "paths": document_paths or [],
            "workspace": workspace,
            "extensions": [".pdf", ".docx", ".xlsx", ".pptx", ".doc", ".csv", ".txt"]
        },
        "knowledge": {
            "json_path": "./domain_knowledge.json",
            "log_path": "./logs/",
            "export_path": "./exports/"
        },
        "crystallization": crystallization_settings,
        "domain_builder": {
            "enabled": False,
            "admin_key_required": True
        }
    }

    return config


def save_config(config: dict, output_path: str) -> str:
    """Saves the config.yaml to a file."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    # Add YAML header comment
    header = "# {domain} domain configuration\n# Auto-generated by Domain Builder\n\n".format(
        domain=config.get("domain", {}).get("display_name", "")
    )

    yaml_content = yaml.dump(config, allow_unicode=True, default_flow_style=False, sort_keys=False)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(yaml_content)

    return output_path


def format_config_preview(config: dict) -> str:
    """Converts the config into a preview format for display to the user."""
    preview = "## Domain Configuration Preview\n\n"
    preview += f"- **Name:** {config['domain']['name']}\n"
    preview += f"- **Display Name:** {config['domain']['display_name']}\n"
    preview += f"- **Workspace:** {config['documents']['workspace']}\n"
    preview += f"- **Document Folders:** {len(config['documents']['paths'])}\n"

    for path in config['documents']['paths']:
        preview += f"  - `{path}`\n"

    preview += f"\n**Crystallization Settings:**\n"
    cs = config.get('crystallization', {})
    promo = cs.get('promotion', {})
    preview += f"- Auto-promotion: {'enabled' if promo.get('auto_promote', False) else 'disabled'}\n"
    preview += f"- Minimum usage count: {promo.get('min_usage', 5)} times\n"
    preview += f"- Minimum success rate: {promo.get('min_success_rate', 0.8):.0%}\n"

    return preview
