"""
process.md Refinement Engine (Design Doc 4.1.4 Phase 1)

Refines process.md based on frameworks.
- Provides frameworks.md as an LLM reference
- LLM reads process.md and selects a framework
- LLM refines through interactive consulting-style questions
- No hardcoded questions — all questions are generated by the LLM to fit the domain context

Usage:
    # Phase 1 - Step 1: Framework selection
    prompt = build_framework_selection_prompt(domain_dir)
    # -> Return to agent -> LLM selects + explains reasoning -> User approval

    # Phase 1 - Step 2: Interactive consulting (no tool calls, LLM conducts directly via conversation)

    # Phase 1 - Step 3: Save
    save_refined_process(domain_dir, content)
"""

from pathlib import Path


# frameworks.md path (same folder as this file)
_THIS_DIR = Path(__file__).resolve().parent
FRAMEWORKS_PATH = _THIS_DIR / "frameworks.md"
SCAR_GUIDE_PATH = _THIS_DIR / "scar_guide.md"


def _read_file(path: Path) -> str:
    """Reads and returns file content. Returns empty string if file doesn't exist."""
    if path.exists():
        return path.read_text(encoding='utf-8')
    return ""


def build_framework_selection_prompt(domain_dir: str) -> str:
    """Phase 1 - Step 1: Generates a framework selection prompt.

    Combines frameworks.md + process.md + scar_guide.md to return a prompt
    that enables the LLM to select a framework and explain the reasoning.

    Args:
        domain_dir: Domain folder path (e.g., "domains/my-domain")

    Returns:
        Prompt string to pass to the LLM
    """
    process_path = Path(domain_dir) / "process.md"
    process_content = _read_file(process_path)
    frameworks_content = _read_file(FRAMEWORKS_PATH)
    scar_guide_content = _read_file(SCAR_GUIDE_PATH)

    if not process_content:
        return f"process.md not found: {process_path}"

    prompt = f"""You are a process consultant.

## Step 1: Framework Selection

Read the process.md below and select the most suitable framework from the 7 available for this business process.

### After Selection:
1. Explain the selected framework and reasoning to the user.
2. For complex processes, you may select a primary + secondary framework.
3. Also ask the user: "What display name should we use for this domain?"
4. Get user approval.

### After Approval (Step 2 — Interactive Consulting):
- Refer to the selected framework's methodology and question directions to refine through natural conversation tailored to the process.md context.
- For content already in process.md, use confirmation questions ("It says ~, could you elaborate on...")
- For content missing from process.md, use exploratory questions ("There's no mention of ~, how do you...")
- Ask 2-3 questions at a time in a natural conversational tone.
- Never ask framework questions verbatim. Adapt them to fit the domain context.

### Completion Criteria:
Refinement is complete when process.md has all the information needed to fill each section of the skill.md universal skeleton below.
- Role: Who is it for and what does it do
- Process: Information that satisfies the selected framework's process structure guide
- Knowledge extraction fields: Items to extract from conversations (based on domain_knowledge.json)
- Result criteria: How to distinguish success/failure for a single task
- Rules: Constraints, escalation criteria

### After Refinement:
Organize the refined content, get user confirmation, and save with the save_refined_process tool.

---

## 7 Framework Details (Reference)

{frameworks_content}

---

## skill.md Writing Principles (Completion Criteria Reference)

{scar_guide_content}

---

## Current process.md

{process_content}
"""
    return prompt


def save_refined_process(domain_dir: str, content: str) -> str:
    """Phase 1 - Step 3: Saves the refined process.md.

    Args:
        domain_dir: Domain folder path
        content: Refined process.md content

    Returns:
        Saved file path
    """
    output_path = Path(domain_dir) / "process.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding='utf-8')
    return str(output_path)
