"""
Auto-Promotion Module

Reflects verified knowledge into skill.md based on usage_stats.

Promotion criteria (per design doc):
- 5+ uses
- 80%+ success rate
- source = "conversation" (only items accumulated from conversations)

Promotion method:
- Automatic (does not wait for approval)
- Included in the weekly report as "N promotions" (for reference)
- If there's an issue, "remove this" (exception handling)

Usage:
    promoted = auto_promote(
        knowledge_json_path="domains/my-domain/domain_knowledge.json",
        skill_md_path="domains/my-domain/skill.md"
    )
"""

import json
from datetime import datetime, timezone, timedelta
from pathlib import Path

KST = timezone(timedelta(hours=9))


def find_promotion_candidates(
    knowledge_json_path: str,
    min_usage: int = 5,
    min_success_rate: float = 0.8
) -> list[dict]:
    """Finds items that meet promotion criteria.

    Among items accumulated from conversations (source=conversation),
    returns only those with usage count and success rate above thresholds.
    """
    path = Path(knowledge_json_path)
    if not path.exists():
        return []

    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    candidates = []
    for item in data.get("items", []):
        # Items from Excel are already reflected -> skip
        if item.get("source") != "conversation":
            continue

        stats = item.get("usage_stats", {})
        if (stats.get("suggested", 0) >= min_usage and
                stats.get("success_rate", 0) >= min_success_rate):
            candidates.append(item)

    return candidates


def generate_skill_update(candidates: list[dict]) -> str:
    """Converts promotion candidates into a markdown block to append to skill.md.

    Returns:
        Markdown text to append to skill.md
    """
    if not candidates:
        return ""

    now = datetime.now(KST)
    update = f"\n\n## Auto-Promoted Knowledge ({now.strftime('%Y-%m-%d')})\n\n"
    update += "*This section was auto-generated by Knowledge Crystallization.*\n\n"

    for item in candidates:
        stats = item["usage_stats"]
        update += f"### {item.get('id', '?')}\n"

        for key in ["description", "cause", "solution", "error_code", "category", "model"]:
            value = item.get(key, "")
            if value:
                update += f"- **{key}:** {value}\n"

        update += f"- **Verified:** used {stats['suggested']} times, success rate {stats['success_rate']:.0%}\n"
        update += f"- **Source:** accumulated from conversations (author: {item.get('created_by', '?')})\n\n"

    return update


def auto_promote(
    knowledge_json_path: str,
    skill_md_path: str,
    min_usage: int = 5,
    min_success_rate: float = 0.8
) -> dict:
    """Executes auto-promotion.

    1. Find promotion candidates
    2. Append block to skill.md
    3. Change promoted items' source to "promoted"

    Returns:
        {"promoted": N, "items": [...]}
    """
    candidates = find_promotion_candidates(
        knowledge_json_path, min_usage, min_success_rate
    )

    if not candidates:
        return {"promoted": 0, "items": []}

    # Append to skill.md
    skill_path = Path(skill_md_path)
    if not skill_path.exists():
        return {"error": f"skill.md not found: {skill_md_path}"}

    update_block = generate_skill_update(candidates)
    if update_block:
        with open(skill_path, 'a', encoding='utf-8') as f:
            f.write(update_block)

    # Change source of promoted items
    kj_path = Path(knowledge_json_path)
    with open(kj_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    promoted_ids = {c["id"] for c in candidates}
    for item in data.get("items", []):
        if item.get("id") in promoted_ids:
            item["source"] = "promoted"
            item["promoted_at"] = datetime.now(KST).isoformat()

    # Backup then save
    import shutil
    try:
        shutil.copy2(kj_path, str(kj_path) + ".bak")
    except Exception:
        pass

    with open(kj_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    return {
        "promoted": len(candidates),
        "items": [{"id": c["id"], "description": c.get("description", "")[:50]} for c in candidates]
    }


def demote(
    knowledge_json_path: str,
    skill_md_path: str,
    item_id: str
) -> dict:
    """Rolls back a promoted item. (Handles "remove this" requests)

    1. Reverts source to "conversation" in knowledge.json
    2. Removes the corresponding block from skill.md (manual)

    Note: Automatic removal from skill.md is not implemented.
    The user should manually delete the section or re-run Domain Builder.
    """
    path = Path(knowledge_json_path)
    if not path.exists():
        return {"error": f"JSON not found: {knowledge_json_path}"}

    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    found = False
    for item in data.get("items", []):
        if item.get("id") == item_id and item.get("source") == "promoted":
            item["source"] = "conversation"
            if "promoted_at" in item:
                del item["promoted_at"]
            found = True
            break

    if not found:
        return {"error": f"Promoted item not found: {item_id}"}

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    return {
        "status": "demoted",
        "item_id": item_id,
        "note": "Please manually delete the corresponding section from skill.md."
    }
